### ISSUE TITLE
Version 5.0 problems

### ISSUE THREAD

**Issue by newbiemmxvii** [tananaev/traccar-client-ios#58]
Version 4.2 worked like a charm.
Version 5.0 doesn't work anymore.
Re-installs didn't help either.
Battery is above 90%.
Default settings used, except Traccar server
After install the dialog to grant permission to access GPS shows up immediately but too short to be answered.
Needed to use privacy settings to permit Traccar client to access GPS
Service stops right after the phone goes to sleep, i.e. requiring the PIN to re-gain access.
The fact that the service stopped is not shown (updated) in the app settings dialog (looks like service is still active). Deactivating and activating the service makes the game to start over.
iPhone 6s, iOS 10.3.3

**Comment by tananaev** [comment]
Can you get system logs from your phone?

**Comment by newbiemmxvii** [comment]
Will try, a hint how to get it would be appreciated, e.g. a link with es description

**Comment by tananaev** [comment]
Maybe this would help:

https://www.theiphonewiki.com/wiki/System_Log

**Comment by newbiemmxvii** [comment]
Thanks, will look into it and share what I find

**Comment by newbiemmxvii** [comment]
Please check your traccar eMail inbox.

**Comment by tananaev** [comment]
I have checked logs and looks like app gets suspended:
```
Sep 16 17:24:56 iPhone mediaserverd(CoreMedia)[27] <Notice>: -CMSessionMgr- cmsmHandleApplicationStateChange: CMSession: Client org.traccar.client.TraccarClient with pid '443' is now Background Suspended. Background entitlement: NO
Sep 16 17:24:56 iPhone mediaserverd(AudioToolbox)[27] <Notice>: 1130: pid 443(TraccarClient)
Sep 16 17:24:56 iPhone mediaserverd(AudioToolbox)[27] <Notice>: 3147: sid:0x1b198, TraccarClient(443), 'prim' new state = Background Task Suspended
```

There are also some network issues:
```
Sep 16 17:25:02 iPhone TraccarClient(libsystem_network.dylib)[443] <Error>: nw_socket_get_input_frames recvmsg(fd 12, 1024 bytes): [57] Socket is not connected
...
Sep 16 17:25:02 iPhone TraccarClient(CFNetwork)[443] <Error>: TIC Read Error [4:0x170189720]: 1:57
Sep 16 17:25:02 iPhone TraccarClient(CFNetwork)[443] <Error>: TIC Read Error [4:0x170189720]: 1:57
```

Unfortunately it doesn't really help much to understand what's happening.

I am also investigating some crash issues. Maybe it's related to your problem.

**Comment by newbiemmxvii** [comment]
Thank you! 

Why does the first log entry (you referenced) state: _Background entitlement: NO_

Regarding networking I would want to understand what the traccar client is trying to achieve. The firewall might be an issue if dedicated (nonstandard) ports are used.

**Comment by tananaev** [comment]
I'm not really sure what those logs mean. I was also a bit surprised by no background entitlement, but maybe it supposed to work like that.

I have uploaded a new version to the App Store. Hopefully it solves some problems. It's waiting for Apple review and should be available in a couple of days.

**Comment by newbiemmxvii** [comment]
I would doubt that might be supposed to work like that. The semantics of _Background entitlement: NO_ makes me believe that the app is not supposed to keep running in the background.

This might give some insight:

https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

Sections _Declaring Your App’s Supported Background Tasks_ and  _Tracking the User’s Location_

My apologies if the link references well known basic stuff

**Comment by tananaev** [comment]
Of course it's well known. We use `location` option from there. I guess log is for other type of background entitlement.

**Comment by newbiemmxvii** [comment]
Update:

 An iPhone 5s is affected identically by the same problem .

Hint:
Tracking is NOT suspended when the status page is kept open, i.e. the position update log entries can be observed before entering idle mode.
Tracking is suspended when the Traccar Client tab (with all configuration options) is open and the phone goes into idle mode.

**Comment by tananaev** [comment]
I have updated the app. Please try version 5.1. It is waiting for Apple review and should be available in a couple of days if everything goes well.

**Comment by mwl** [comment]
I have the exact same problem on two separate devices (iOS 10.3.3 and iOS 11) running Traccar Client 5.0 with the only exception that I can't even allow the app to see the location in Settings.app. These are completely new installations and have never been hooked up with any Traccar server before.

**Comment by tananaev** [comment]
Please wait and see if it works on Traccar Client 5.0.

**Comment by mwl** [comment]
Just installed 5.1, and I'm afraid is has changed nothing. The iOS Location permissions dialog comes up for a second or so, before it disappears. In status it says
> Service created
> Service destroyed

I even did a clean install.

**Comment by newbiemmxvii** [comment]
Acknowledgement, no change with 5.1, the problem persists, sorry.
Have to keep it running with the status page compulsory open before it changes to background mode to prevent of "Service destroyed".

**Comment by tananaev** [comment]
Can anyone please send a video of the problem?

**Comment by tananaev** [comment]
Also, please anyone who can help with testing through TestFlight, please send me your email addresses. You can send them to my email address (in profile).

**Comment by mwl** [comment]
Sure, here you go https://youtu.be/09ftaTCLPHk

Sorry I didn’t change the system language, but the pop up dialog is asking for permission to use my location. I’m not responding on it and it goes away by itself.

**Comment by tananaev** [comment]
Please wait for version 5.2. It should definitely be fixed now.

In the meanwhile what you can do is manually enable location permissions for the app from settings.

**Comment by mwl** [comment]
Thanks Anton. I can confirm the workaround works.

**Comment by dpepperd** [comment]
In regard to the popup dialog, I ended up going into settings and just changing the permission there to allow traccar client to use location services. I have not been able to get version 5.1 to run on Ios 11 on the new Iphone 8 at all. Anton if there is anything you need to help you out post it here I'll be glad to do whatever I can.

**Comment by newbiemmxvii** [comment]
Thank you Anton! 5.2 sounds promising.

**Comment by tananaev** [comment]
It should already be available. Please let me know if it works.

**Comment by mwl** [comment]
Sorry to report, that the issue is exactly the same on 5.2.

Another thing I've noticed with 5.1 over the weekend was that tracking only works with you leave the app in the Status view.

**Comment by dpepperd** [comment]
Same issues with 5.2 on iOS 11 and iPhone 8. App is not working.

**Comment by tananaev** [comment]
OK, I believe at least one of the problems should be fixed now. Permissions dialog should function correctly now. Please confirm.

As for the other problem, it's a mystery. I have no idea why it works if you open status screen but not on the main screen. For now my suspicion is that Apple did some "optimization" which causes this behavior. Is the behavior same for everyone? How long does app report with locked screen? Does it stop reporting instantly?

**Comment by mwl** [comment]
> OK, I believe at least one of the problems should be fixed now. Permissions dialog should function correctly now. Please confirm.

It is _still_ the same issue. Dialog shows up for a second, then disappears again by itself.

**Comment by tananaev** [comment]
Are you sure you are using version 5.2? I definitely fixed that problem. Tested on iPhone 7.

**Comment by dpepperd** [comment]
Issue still exists on ios 11 and iphone 8. Dialog box pops up and goes away
quickly.

**Comment by mwl** [comment]
> Are you sure you are using version 5.2? I definitely fixed that problem. Tested on iPhone 7.

For as long as I deleted the app and reinstalled it through the App Store after confirming that 5.2 was available. So pretty sure, yes :)

**Comment by pmlewisuk** [comment]
Hi

Iphone 6 IOS 10

With version 5.1 I found the service was destroyed when I exited the app, if I left it on the status screen and exited it was OK 

I updated to 5.2 and it was always immediately destroying so I uninstalled and then did a fresh 5.2 install.
Now the Allow 'Traccar Client' to Access flashes up and disappears, if I do manage to say allow I get service destroyed. It doesn't remember the 'Allow' and doesn't show in the privacy location services since the reinstall.

Hope this help you.

Regards

Mark

**Comment by tananaev** [comment]
Really hard to debug issues without real iPhone device on hands. Anyway, I think I have fixed (again) the problem with disappearing dialog. Please check version 5.3 which should be available in a couple of days.

This time I tested on Amazon device farm on iPhone 5s with iOS 10.3.3.

**Comment by dpepperd** [comment]
Anton,

If you want help testing I have an iPhone 8 and would be glad to help you.

**Comment by ashishnaicker** [comment]
Same issue on iPhone 6 Plus, iOS 10.3.3, Traccar Client 5.2
- allow location dialog opens and closes almost immediately
- service starts and destroyed almost immediately
- device appears offline on demo server

**Comment by wouterbudding** [comment]
I have the same on an iPhone 8 and on an iPhone 7, both with iOS 11 and iOS 11.0.1 , both Version 5.2 of the app. Please see attachment. aangemaakt = created and gestopt = stopped
![s](https://user-images.githubusercontent.com/22468456/30934876-3949f60c-a3cf-11e7-9805-7183d3e9c031.jpg)

**Comment by tananaev** [comment]
Please check version 5.3. it's already under review, so hopefully it will be available in a few hours.

**Comment by tananaev** [comment]
I just got notification that version 5.3 is out. Please let me know if it fixes the issues.

**Comment by dpepperd** [comment]
I just went in App Store and 5.2 still showing up 9/27 at 19:23 EST.  I
will keep checking thanks.

**Comment by pmlewisuk** [comment]
Just installed and tested, looking good 😊 

Will keep testing today

Thanks 

Sent from my iPhone

On 28 Sep 2017, at 00:24, dpepperd <notifications@github.com> wrote:

I just went in App Store and 5.2 still showing up 9/27 at 19:23 EST. I
will keep checking thanks.

**Comment by newbiemmxvii** [comment]
Thank you Anton! Works fine for me. ***** The service doesn't stop anymore when the app is sent to background without showing the status page. I didn't test the dialog to grant GPS access though as I would have to reinstall the app and reenter the configuration, sorry. I trust it works.

This ticket could be closed in my eyes. Thank you again!

**Comment by tananaev** [comment]
Great, thanks everyone for feedback.
